# Parent Devfile
schemaVersion: 2.1.0
metadata:
  name: devfile-test
components:
  - name: db-service
    container:
      image: "bitnami/postgresql:12.5.0"
      env:
        - value: root
          name: POSTGRES_USER
        - value: password
          name: POSTGRES_PASSWORD
      memoryLimit: 256Mi
